#!/usr/bin/env python
import cv2
import numpy as np 
from PIL import Image
import roslib


import roslib
roslib.load_manifest('facedetector')
import rospy
import sys, select, termios, tty
import cv
import time
import Image
import os
import cv2, numpy
from std_msgs.msg import String
from std_msgs.msg import Bool
import sensor_msgs.msg
from dynamic_reconfigure.server import Server as DynamicReconfigureServer
from detection_msgs.msg import Detection
from cv_bridge import CvBridge, CvBridgeError
from sensor_msgs.msg import Image

class Faces():
	def face_callback(self, data):
		#print("v call back")
		if(time.time() - self.cas > 1 ):
			#print("berem image")

			n = 1
			#image = numpy.zeros((self.face_size * n, self.face_size), dtype=numpy.uint8)
			try:

				for i in xrange(0, n):
					image = self.bridge.imgmsg_to_cv2(data.image, "bgr8")
					image = cv2.resize(image, (50, 50)) 
					equb,equg,equr = cv2.split(image)
					equb = cv2.equalizeHist(equb)
					equg = cv2.equalizeHist(equg)
					equr = cv2.equalizeHist(equr)
					image = cv2.merge((equb,equg,equr))
					
					#cv2.imwrite("/home/team_zeta/slikeZ/"+str(100)+".png", equ)
					self.recognize(np.array(image).flatten().tolist())
					self.cas = time.time()
			except CvBridgeError, e:
				print e


	def read_images(self,urls):
		try:
			image_paths = [os.path.join("/home/team_zeta/catkin_ws/src/slikeZ/", f) for f in os.listdir("/home/team_zeta/catkin_ws/src/slikeZ/")]
		except Exception as inst:
			image_paths = [os.path.join("/home/boka/catkin_ws/src/slikeZ/", f) for f in os.listdir("/home/boka/catkin_ws/src/slikeZ/")]
		images = []
		labels = []
		print(image_paths[0])
		for url in image_paths:
			#images += [cv2.imread(url)]
			equ = cv2.imread(url)
			equ = cv2.resize(equ, (50, 50)) 
			equb,equg,equr = cv2.split(equ)
			equb = cv2.equalizeHist(equb)
			equg = cv2.equalizeHist(equg)
			equr = cv2.equalizeHist(equr)
			image = cv2.merge((equb,equg,equr))
			images += [np.array(image).flatten().tolist()]
			print(os.path.split(url)[1].split(".")[1])
			nbr = int(os.path.split(url)[1].split(".")[1].split("-")[1])
			labels += [nbr]
		return [images, labels]


	def learn(self):
		try:
			[images, labels] = self.read_images("/home/team_zeta/catkin_ws/src/slikeZ/")
		except Exception as inst:
			[images, labels] = self.read_images("/home/boka/catkin_ws/src/slikeZ/")
		print("ucim se, pocakaj..")
		print(np.array(images))
		print(len(np.array(images)[0]))
		print(len(np.array(images)))
		print labels
		self.recognizer.train(np.array(images).astype(np.float32), np.array(labels).astype(np.float32))
		#self.recognizer.save("/home/boka/model/model.yaml")

	def recognize(self,image):
		print(np.array([image]).astype(np.float32))
		ret, nbr_predicted, neighbours, dist = self.recognizer.find_nearest(np.array([image]).astype(np.float32), k=5)
		print("predicted" + str(nbr_predicted))
		print("coef"+str(dist))

	def __init__(self):
		self.recognizer = cv2.KNearest()
		#self.recognizer = cv2.createFisherFaceRecognizer()
		print("ucim")
		self.learn()
		print("naucil")
		faces_topic = rospy.get_param('~topic', rospy.resolve_name('/detector/traffic_signs'))
		
		self.face_size = rospy.get_param('~face_size', 128)

		self.bridge = CvBridge()
		self.faces_sub = rospy.Subscriber(faces_topic, Detection, self.face_callback)
		self.cas = time.time()



# Main function.    
if __name__ == '__main__':
	print("v main")
	rospy.init_node('znakreco')

	try:
		fd = Faces()
		r = rospy.Rate(0.2)
		while not rospy.is_shutdown():
			r.sleep()
	except rospy.ROSInterruptException: pass


